source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSSmartBus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    platform :ios, '7.0' # (or '9.0' or '10.0')
    pod "PubNub", "~> 4"
    pod 'GoogleMaps'
    pod 'GooglePlaces'
  # Pods for iOSSmartBus

  target 'iOSSmartBusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSSmartBusUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
